# -*- coding: utf-8 -*-
"""ADAML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13im8xzvl4eIY4zLPjfRMkXlnpcwqLWRX
"""

import pandas as pd

WT2 = pd.read_excel('/content/sample_data/data.xlsx', 'No.2WT')
WT39 = pd.read_excel('/content/sample_data/data.xlsx', 'No.39WT')
WT14 = pd.read_excel('/content/sample_data/data.xlsx', 'No.14WT')
WT3 = pd.read_excel('/content/sample_data/data.xlsx', 'No.3')

WT2 = WT2.iloc[:, :-1] # WT2 has extra variable at the end


turbines = [WT2, WT39, WT14, WT3]
for turbine in turbines:
  missing_values = turbine.isnull().sum()
  record_count = len(turbine)
  means = turbine.mean()
  print(f"Number of missing values{missing_values}")
  print(f"Number of records {record_count}")
  print(means)

import matplotlib.pyplot as plt

corr_matrix_2 = WT2.corr()
#print(corr_matrix_2)

plt.imshow(corr_matrix_2, cmap='Blues')

corr_matrix_39 = WT39.corr()
#print(corr_matrix_2)

plt.imshow(corr_matrix_39, cmap='Blues')

corr2 = WT39.corrwith(WT2)
print(corr2)

X = pd.concat([WT2, WT39], axis=1);
corr_matrix_both = X.corr()
plt.imshow(corr_matrix_both, cmap='Blues')

import seaborn as sns
sns.heatmap(WT2.corrwith(WT39).to_frame(), annot=True, cmap="coolwarm")

WT2 = pd.read_excel('/content/sample_data/data.xlsx', 'No.2WT')
WT39 = pd.read_excel('/content/sample_data/data.xlsx', 'No.39WT')
for column in WT39.columns:
  plt.figure()
  plt.boxplot([WT2[column],WT39[column]])
  plt.title(f'Boxplot of {column}')
  plt.grid(True)
  plt.show()

plt.figure()
plt.boxplot(WT2[28])
plt.title(f"Boxplot of 28")
plt.grid(True)
plt.show()

# chosen variables to look into: 5, 11, 12, 15, 18, 27

picked_columns = [5, 11, 12, 15, 18, 27]
for col in picked_columns:
  plt.figure()
  plt.plot(WT2.iloc[:, col-1], label="WT2", color='blue')
  plt.plot(WT39.iloc[:, col-1], label="WT39", color='green')
  plt.title(f"Time series of attribute {col}")
  plt.xlabel("Time")
  plt.grid(True)